# Generated by Django 3.0.8 on 2020-07-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200709_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='starting_bid',
            new_name='bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='current_bid',
        ),
    ]
